# Parameter deamon for Hyperledger under swarm

FROM stylix/hyperledger:latest

MAINTAINER Siriwat K.

# Node.js installation
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - \
        && apt-get install -y nodejs

COPY ./param_daemon/server /param_daemon/server/

CMD ["node","/param_daemon/server/server.js","10101"]